Include option to decrypt values on pull
nandi95/laravel-env-in-aws-ssm pull request #2
Opened 2024-07-03 19:28 UTC by picheidt

Hi there!

First off, thanks for making this awesome library! I'm currently using it in my project and it's been incredibly helpful. While working with it, I noticed an opportunity to enhance its functionality a bit.

I’d like to contribute by adding an option to decrypt values when accessing them using SSM. This addition would be super useful for scenarios where encrypted data needs to be seamlessly integrated.

2024-07-04 08:12 UTC, nandi95 requested changes

2024-07-04 08:12 UTC, nandi95 commented on README.md
> + - `--decrypt`(optional | Only in pull action) - Decrypt the values before pulling them.
Perhaps you could include a link to the encrypt part of the documentation?
Maybe this: https://docs.aws.amazon.com/kms/latest/developerguide/services-parameter-store.html

2024-07-04 08:12 UTC, nandi95 commented on src/Traits/InteractsWithSSM.php
> +            'WithDecryption' => $decrypt,
looks good

2024-07-04 08:12 UTC, nandi95 commented on src/Traits/InteractsWithSSM.php
> +    public function getEnvironmentVarsFromRemote(string $nextToken = null, bool $decrypt = false): Collection
this doesn't seem to be passed into this function anywhere so it's always false?

2024-07-04 08:12 UTC, nandi95 commented on src/Traits/InteractsWithSSM.php
> +    public function getEnvironmentVarsFromRemote(string $nextToken = null, bool $decrypt = false): Collection
consider using it from the context `$this->decrypt` given that it would go after the next token argument.

2024-07-04 08:12 UTC, nandi95 commented on src/Console/EnvPull.php
> +        $this->decrypt = $this->option('decrypt') ? true : false;
this will need to be implemented for the list and push command too I believe. (anywhere where the `getEnvironmentVarsFromRemote` is used)

2024-07-04 11:30 UTC, picheidt commented
I made the requested changes. Could you tell me when the new version will be available for download using composer?

2024-07-04 20:58 UTC, merged

2024-07-04 22:22 UTC, nandi95 commented
@picheidt Released, let me know if it all works or doesn't.

2024-07-05 12:04 UTC, picheidt commented
> @picheidt Released, let me know if it all works or doesn't.

I tested some cases here and everything looks good!